# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2701f7fd-4969-40f3-a930-f7b0e52fef48";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/50869e25-ac4e-487e-a471-faae5d57626e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/41A4-CA82";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home/mikel" = {
    device = "/dev/disk/by-uuid/2701f7fd-4969-40f3-a930-f7b0e52fef48";
    fsType = "btrfs";
    options = [ "subvol=mikel" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/2701f7fd-4969-40f3-a930-f7b0e52fef48";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/2701f7fd-4969-40f3-a930-f7b0e52fef48";
    fsType = "btrfs";
    options = [ "subvol=swap" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/2701f7fd-4969-40f3-a930-f7b0e52fef48";
    fsType = "btrfs";
    options = [ "subvol=tmp" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/2701f7fd-4969-40f3-a930-f7b0e52fef48";
    fsType = "btrfs";
    options = [ "subvol=log" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
