# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [
    "ata_piix"
    "ohci_pci"
    "ehci_pci"
    "ahci"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2d8f4dd6-31e0-4abf-bb12-b891708ca865";
    fsType = "btrfs";
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/2d8f4dd6-31e0-4abf-bb12-b891708ca865";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/2d8f4dd6-31e0-4abf-bb12-b891708ca865";
    fsType = "btrfs";
    options = [ "subvol=var" ];
  };

  fileSystems."/virtualboxshare" = {
    device = "WD_Black";
    fsType = "vboxsf";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/2d8f4dd6-31e0-4abf-bb12-b891708ca865";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/2d8f4dd6-31e0-4abf-bb12-b891708ca865";
    fsType = "btrfs";
    options = [ "subvol=tmp" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C91A-373D";
    fsType = "vfat";
  };

  fileSystems."/mnt/WD_Black" = {
    device = "WD_Black";
    fsType = "vboxsf";
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  virtualisation.virtualbox.guest.enable = true;
}
